version: "2"
services:
  varnish:
    container_name: servicoVarnishMultiSites
    restart: always
    build:
      context: ./dockerfileVarnish
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./confs:/etc/varnish/conf.d/
    ports:
      - "${PORTA_WEB}:6081"
#    - "6085:6085"
    networks:
      redecachewp:
        aliases:
          - cacheServer
    depends_on:
      - siteExemplo1
      - siteExemplo2
      - siteExemplo3  
    environment:  
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "admin"
      DASHBOARD_PASSWORD: "admin"
      DASHBOARD_SERVERS: "varnish"
      DASHBOARD_DNS_ENABLED: "true"
  siteExemplo1:
    image: eeacms/hello
    environment:
      PORT: "8080"
    networks:
      redecachewp:
        aliases:
          - siteExemplo1
  siteExemplo2:
    image: eeacms/hello
    environment:
      PORT: "8080"
    networks:
      redecachewp:
        aliases:
          - siteExemplo2
  siteExemplo3:
    image: eeacms/hello
    environment:
      PORT: "8081"
    networks:
      redecachewp:
        aliases:
          - download
networks:
  redecachewp:
