version: "2"
services:
  varnish:
    container_name: servicoVarnishMultiSites
    restart: always
    build:
      context: ./dockerfileVarnish
      dockerfile: Dockerfile
    volumes:
      - ./confs:/etc/varnish/conf.d/
    ports:
    - "80:6081"
#    - "6085:6085"
    env_file:
    - envExemplo
    - .env
    environment:  
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "admin"
      DASHBOARD_PASSWORD: "admin"
      DASHBOARD_SERVERS: "varnish"
      DASHBOARD_DNS_ENABLED: "true"
 
