version: "2"
services:
  varnishinicio:
   image: casanovadigital:varnishVCLinit
   volumes:
     - ./conf.d/:/etc/varnish/conf.d/:z
     - ./sitesPublicados:/var/varnish/sitesPublicados/:z
  varnish:
    container_name: servicoVarnishMultiSites
    restart: always
    image: casanovadigital:varnishCacheMultiSite
    env_file:
      - .env
    depends_on:
      - varnishinicio
    volumes:
      - ./conf.d/:/etc/varnish/conf.d/:Z
      - ./sitesPublicados:/var/varnish/sitesPublicados/:Z
    ports:
      - "${PORTA_WEB}:6081"
      - "6085:6085"
    networks:
      redecachewp:
        aliases:
          - cacheServer
    environment:  
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_SERVERS: "varnish"
      DASHBOARD_DNS_ENABLED: "true"
    
networks:
  redecachewp:
