version: "2"
services:
  varnishinicio:
   image: casanovadigital:varnishVCLinit
   volumes:
     - ./conf.d/:/etc/varnish/conf.d/:z
     - ./sitesPublicados:/var/varnish/sitesPublicados/:z
  varnishcndproxys3:
    image: casanovadigital:CNDProxyS3
    restart: always
    networks:
      redecachewp:
        aliases:
          - cndproxys3

#    healthcheck:
#      test: ["CMD", "curl", "-f", "https://google.com.br"]
#      interval: 30s
#      timeout: 10s
#      retries: 3 
#TODO ADICIONAR HEALTHSTATE pois  o cprreto é o varnish iniciar apenas depois do init terminar a execução
# da forma como está só funciona devido a falha de carregamento do script quando o varniosh é iniciado pela metade, se não ocorrer falha 
# o script incplmpleto será  iniciado 
  varnish:
    container_name: servicoVarnishMultiSites
    restart: always
    image: casanovadigital:varnishCacheMultiSite
    env_file:
      - .env
    depends_on:
      - varnishinicio
    volumes:
      - ./conf.d/:/etc/varnish/conf.d/:Z
      - ./sitesPublicados:/var/varnish/sitesPublicados/:z
    ports:
      - "${PORTA_WEB}:6081"
      - "6085:6085"
    networks:
      redecachewp:
        aliases:
          - cacheServer
    environment:  
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_SERVERS: "varnish"
      DASHBOARD_DNS_ENABLED: "true"
    
networks:
  redecachewp:



